<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CantonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sql  = "ALTER SEQUENCE canton_id_seq RESTART WITH 1;";
        $sql .= 'TRUNCATE canton CASCADE;';
        DB::connection()->getPdo()->exec($sql);

        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('101','1','Cuenca',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('102','1','Giron',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('103','1','Gualaceo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('104','1','Nabon',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('105','1','Paute',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('106','1','Pucara',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('107','1','San Fernando',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('108','1','Santa Isabel',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('109','1','Sigsig',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('110','1','Oña',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('111','1','Chordeleg',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('112','1','El Pan',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('113','1','Sevilla De Oro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('114','1','Guachapala',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('115','1','Camilo Ponce Enriquez',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('201','2','Guaranda',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('202','2','Chillanes',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('203','2','Chimbo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('204','2','Echeandia',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('205','2','San Miguel',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('206','2','Caluma',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('207','2','Las Naves',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('301','3','Azogues',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('302','3','Biblian',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('303','3','Cañar',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('304','3','La Troncal',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('305','3','El Tambo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('306','3','Deleg',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('307','3','Suscal',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('401','4','Tulcan',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('402','4','Bolivar',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('403','4','Espejo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('404','4','Mira',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('405','4','Montufar',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('406','4','San Pedro De Huaca',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('501','5','Latacunga',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('502','5','La Mana',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('503','5','Pangua',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('504','5','Pujili',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('505','5','Salcedo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('506','5','Saquisili',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('507','5','Sigchos',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('601','6','Riobamba',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('602','6','Alausi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('603','6','Colta',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('604','6','Chambo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('605','6','Chunchi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('606','6','Guamote',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('607','6','Guano',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('608','6','Pallatanga',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('609','6','Penipe',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('610','6','Cumanda',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('701','7','Machala',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('702','7','Arenillas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('703','7','Atahualpa',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('704','7','Balsas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('705','7','Chilla',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('706','7','El Guabo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('707','7','Huaquillas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('708','7','Marcabeli',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('709','7','Pasaje',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('710','7','Piñas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('711','7','Portovelo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('712','7','Santa Rosa',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('713','7','Zaruma',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('714','7','Las Lajas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('801','8','Esmeraldas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('802','8','Eloy Alfaro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('803','8','Muisne',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('804','8','Quininde',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('805','8','San Lorenzo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('806','8','Atacames',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('807','8','Rio Verde',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('901','9','Guayaquil',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('902','9','Alfredo Baquerizo Moreno',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('903','9','Balao',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('904','9','Balzar',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('905','9','Colimes',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('906','9','Daule',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('907','9','Duran',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('908','9','El Empalme',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('909','9','El Triunfo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('910','9','Milagro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('911','9','Naranjal',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('912','9','Naranjito',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('913','9','Palestina',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('914','9','Pedro Carbo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('916','9','Samborondon',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('918','9','Santa Lucia',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('919','9','Salitre',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('920','9','San Jacinto De Yaguachi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('921','9','Playas // (General Villamil)',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('922','9','Simon Bolivar',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('923','9','Coronel Marcelino Maridueña',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('924','9','Lomas De Sargentillo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('925','9','Nobol // (Vicente Piedrahita)',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('927','9','General Antonio Elizalde',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('928','9','Isidro Ayora',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1001','10','Ibarra',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1002','10','Antonio Ante',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1003','10','Cotacachi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1004','10','Otavalo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1005','10','Pimampiro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1006','10','San Miguel De Urcuqui',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1101','11','Loja',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1102','11','Calvas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1103','11','Catamayo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1104','11','Celica',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1105','11','Chahuarpamba',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1106','11','Espindola',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1107','11','Gonzanama',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1108','11','Macara',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1109','11','Paltas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1110','11','Puyango',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1111','11','Saraguro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1112','11','Sozoranga',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1113','11','Zapotillo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1114','11','Pindal',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1115','11','Quilanga',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1116','11','Olmedo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1201','12','Babahoyo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1202','12','Baba',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1203','12','Montalvo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1204','12','Pueblo Viejo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1205','12','Quevedo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1206','12','Urdaneta',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1207','12','Ventanas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1208','12','Vinces',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1209','12','Palenque',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1210','12','Buena Fe',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1211','12','Valencia',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1212','12','Mocache',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1213','12','Quinsaloma',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1301','13','Portoviejo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1302','13','Bolivar',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1303','13','Chone',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1304','13','El Carmen',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1305','13','Flavio Alfaro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1306','13','Jipijapa',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1307','13','Junin',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1308','13','Manta',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1309','13','Montecristi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1310','13','Pajan',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1311','13','Pichincha',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1312','13','Rocafuerte',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1313','13','Santa Ana',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1314','13','Sucre',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1315','13','Tosagua',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1316','13','24 De Mayo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1317','13','Pedernales',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1318','13','Olmedo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1319','13','Puerto Lopez',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1320','13','Jama',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1321','13','Jaramijo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1322','13','San Vicente',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1401','14','Morona',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1402','14','Gualaquiza',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1403','14','Limon - Indanza',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1404','14','Palora',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1405','14','Santiago',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1406','14','Sucua',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1407','14','Huamboya',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1408','14','San Juan Bosco',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1409','14','Taisha',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1410','14','Logroño',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1411','14','Pablo Sexto',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1412','14','Tiwintza',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1501','15','Tena',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1503','15','Archidona',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1504','15','El Chaco',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1507','15','Quijos',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1509','15','Carlos Julio Arosemena T.',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1601','16','Pastaza',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1602','16','Mera',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1603','16','Santa Clara',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1604','16','Arajuno',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1701','17','Quito',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1702','17','Cayambe',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1703','17','Mejia',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1704','17','Pedro Moncayo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1705','17','Rumiñahui',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1707','17','San Miguel De Los Bancos',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1708','17','Pedro Vicente Maldonado',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1709','17','Puerto Quito',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1801','18','Ambato',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1802','18','Baños De Agua Santa',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1803','18','Cevallos',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1804','18','Mocha',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1805','18','Patate',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1806','18','Quero',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1807','18','San Pedro De Pelileo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1808','18','Santiago De Pillaro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1809','18','Tisaleo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1901','19','Zamora',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1902','19','Chinchipe',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1903','19','Nangaritza',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1904','19','Yacuambi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1905','19','Yantzaza',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1906','19','El Pangui',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1907','19','Centinela Del Condor',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1908','19','Palanda',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('1909','19','Paquisha',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2001','20','San Cristobal',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2002','20','Isabela',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2003','20','Santa Cruz',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2101','21','Lago Agrio',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2102','21','Gonzalo Pizarro',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2103','21','Putumayo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2104','21','Shushufindi',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2105','21','Sucumbios',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2106','21','Cascales',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2107','21','Cuyabeno',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2201','22','Francisco De Orellana',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2202','22','Aguarico',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2203','22','La Joya De Los Sachas',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2204','22','Loreto',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2301','23','Santo Domingo',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2302','23','La Concordia',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2401','24','Santa Elena',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2402','24','La Libertad',NULL,NULL,NULL);");
        DB::insert("insert into canton (id, provincia_id, nombre, created_at, updated_at, deleted_at) values('2403','24','Salinas',NULL,NULL,NULL);");
    }
}
