<?php

use Illuminate\Database\Seeder;

class TipoSubsectorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $sql  = "ALTER SEQUENCE tipo_subsector_id_seq RESTART WITH 1;";
        $sql .= 'TRUNCATE tipo_subsector CASCADE;';
        DB::connection()->getPdo()->exec($sql);

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('1','1','Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('2','1','Cultivo de arroz',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('3','1','Cultivo de hortalizas y melones, raíces y tubérculos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('4','1','Cultivo de caña de azúcar',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('5','1','Cultivo de tabaco',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('6','1','Cultivo de plantas de fibras',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('7','1','Cultivo de otras plantas no perennes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('8','1','Cultivo de frutas tropicales y subtropicales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('9','1','Cultivo de cítricos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('10','1','Cultivo de frutas con hueso y con pepa',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('11','1','Cultivo de otros frutos y nueces de árboles y arbustos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('12','1','Cultivo de frutos oleaginosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('13','1','Cultivo de plantas con las que se preparan bebidas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('14','1','Cultivo de especias y de plantas aromáticas, medicinales y farmacéuticas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('15','1','Cultivo de otras plantas perennes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('16','1','Propagación de plantas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('17','1','Cría de ganado bovino y búfalos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('18','1','Cría de ovejas y cabras',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('19','1','Cría de cerdos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('20','1','Cría de aves de corral',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('21','1','Cría de otros animales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('22','1','Actividades de apoyo a la agricultura',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('23','1','Actividades de apoyo a la ganadería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('24','1','Actividades poscosecha',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('25','1','Tratamiento de semillas para propagación',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('26','1','Silvicultura y otras actividades forestales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('27','1','Extracción de madera',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('28','1','Servicios de apoyo a la silvicultura',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('29','1','Pesca marina',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('30','1','Pesca de agua dulce',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('31','1','Acuicultura marina',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('32','1','Acuicultura de agua dulce',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('33','2','Extracción de carbón de piedra',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('34','2','Extracción de petróleo crudo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('35','2','Extracción de gas natural',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('36','2','Extracción de otros minerales metalíferos no ferrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('37','2','Extracción de piedra, arena y arcilla',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('38','2','Extracción de sal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('39','2','Explotación de otras minas y canteras n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('40','2','Actividades de apoyo para la extracción de petróleo y gas natural',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('41','2','Actividades de apoyo para la explotación de otras minas y canteras',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('42','3','Elaboración y conservación de carne',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('43','3','Elaboración y conservación de pescados, crustáceos y moluscos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('44','3','Elaboración y conservación de frutas, legumbres y hortalizas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('45','3','Elaboración de aceites y grasas de origen vegetal y animal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('46','3','Elaboración de productos lácteos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('47','3','Elaboración de productos de molinería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('48','3','Elaboración de almidones y productos derivados del almidón',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('49','3','Elaboración de productos de panadería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('50','3','Elaboración de azúcar',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('51','3','Elaboración de cacao, chocolate y productos de confitería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('52','3','Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('53','3','Elaboración de comidas y platos preparados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('54','3','Elaboración de otros productos alimenticios n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('55','3','Elaboración de alimentos preparados para animales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('56','3','Destilación, rectificación y mezcla de bebidas alcohólicas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('57','3','Elaboración de vinos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('58','3','Elaboración de bebidas malteadas y de malta',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('59','3','Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('60','3','Elaboración de productos de tabaco',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('61','3','Preparación e hilatura de fibras textiles',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('62','3','Tejedura de productos textiles',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('63','3','Servicio de acabado de productos textiles',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('64','3','Fabricación de tejidos de punto y ganchillo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('65','3','Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('66','3','Fabricación de tapices y alfombras',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('67','3','Fabricación de cuerdas, cordeles, bramantes y redes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('68','3','Fabricación de otros productos textiles n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('69','3','Fabricación de prendas de vestir, excepto prendas de piel',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('70','3','Fabricación de artículos de piel',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('71','3','Fabricación de artículos de punto y ganchillo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('72','3','Curtido y adobo de cueros; adobo y teñido de pieles',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('73','3','Fabricación de maletas, bolsos de mano y artículos similares, artículos de talabartería y guarnicionería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('74','3','Fabricación de calzado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('75','3','Aserrado y acepilladura de madera',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('76','3','Fabricación de hojas de madera para enchapado y tableros a base de madera',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('77','3','Fabricación de partes y piezas de carpintería para edificios y construcciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('78','3','Fabricación de recipientes de madera',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('79','3','Fabricación de otros productos de madera; fabricación de artículos de corcho, paja y materiales trenzables',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('80','3','Fabricación de pasta de madera, papel y cartón',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('81','3','Fabricación de papel y cartón ondulado y de envases de papel y cartón',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('82','3','Fabricación de otros artículos del papel y cartón',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('83','3','Actividades de impresión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('84','3','Actividades de servicios relacionados con la impresión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('85','3','Reproducción de grabaciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('86','3','Fabricación de productos de la refinación del petróleo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('87','3','Fabricación de substancias químicas básicas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('88','3','Fabricación de abonos y compuestos de nitrógeno',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('89','3','Fabricación de plásticos y de cauchos sintético en formas primarias',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('90','3','Fabricación de plaguicidas y otros productos químicos de uso agropecuario',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('91','3','Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('92','3','Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('93','3','Fabricación de otros productos químicos n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('94','3','Fabricación de fibras artificiales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('95','3','Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('96','3','Fabricación de cubiertas y cámaras de caucho; recauchutado y renovación de cubiertas de caucho',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('97','3','Fabricación de otros productos de caucho',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('98','3','Fabricación de productos de plástico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('99','3','Fabricación de vidrio y productos de vidrio',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('100','3','Fabricación de productos refractarios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('101','3','Fabricación de materiales de construcción de arcilla',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('102','3','Fabricación de otros productos de porcelana y de cerámica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('103','3','Fabricación de cemento, cal y yeso',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('104','3','Fabricación de artículos de hormigón, de cemento y yeso',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('105','3','Corte, tallado y acabado de la piedra',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('106','3','Fabricación de otros productos minerales no metálicos n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('107','3','Industrias básicas de hierro y acero',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('108','3','Fabricación de productos primarios de metales preciosos y metales no ferrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('109','3','Funcidición de hierro y acero',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('110','3','Fundición de metales no ferrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('111','3','Fabricación de productos metálicos para uso estructural',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('112','3','Fabricación de tanques, depósitos y recipientes de metal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('113','3','Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('114','3','Fabricación de armas y municiones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('115','3','Forja, prensado, estampado y laminado de metales; pulvimetalurgia',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('116','3','Tratamiento y revestimiento de metales; maquinado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('117','3','Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('118','3','Fabricación de otros productos elaborados de metal n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('119','3','Fabricación de componentes y tableros electrónicos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('120','3','Fabricación de ordenadores y equipo periférico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('121','3','Fabricación de equipo de comunicaciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('122','3','Fabricación de aparatos electrónicos de consumo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('123','3','Fabricación de equipos de medición, prueba, navegación, control y de relojes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('124','3','Fabricación de relojes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('125','3','Fabricación de equipo de irradiación, y equipo electrónico de uso medico y terapéutico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('126','3','Fabricación de instrumentos ópticos y equipo fotográficos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('127','3','Fabricación de motores, generadores, transformadores eléctricos y aparatos de distribución y control de la energía eléctrica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('128','3','Fabricación de pilas, baterías y acumuladores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('129','3','Fabricación de otros hilos y cables eléctricos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('130','3','Fabricación de dispositivos de cableado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('131','3','Fabricación de equipo eléctrico de iluminación',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('132','3','Fabricación de aparatos de uso doméstico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('133','3','Fabricación de otros tipos de equipo eléctrico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('134','3','Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('135','3','Fabricación de equipo de propulsión de fluidos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('136','3','Fabricación de otras bombas, compresores, grifos y válvulas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('137','3','Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('138','3','Fabricación de hornos y quemadores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('139','3','Fabricación de equipo de elevación y manipulación',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('140','3','Fabricación de maquinaria y equipo de oficina (excepto ordenadores y equipo periférico)',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('141','3','Fabricación de herramientas de mano motorizadas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('142','3','Fabricación de otros tipos de maquinaria de uso general',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('143','3','Fabricación de maquinaria agropecuaria y forestal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('144','3','Fabricación de maquinaria para la conformación de metales y de máquinas herramienta',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('145','3','Fabricación de maquinaria metalúrgica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('146','3','Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('147','3','Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('148','3','Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('149','3','Fabricación de otros tipos de maquinaria de uso especial',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('150','3','Fabricación de vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('151','3','Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('152','3','Fabricación de partes, piezas y accesorios para vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('153','3','Construcción de buques y estructuras flotantes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('154','3','Construcción de embarcaciones de recreo y deporte',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('155','3','Fabricación de locomotoras y material rodante',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('156','3','Fabricación de aeronaves y naves especiales y maquinaria conexa',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('157','3','Fabricación de motocicletas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('158','3','Fabricación de bicicletas y de sillas de ruedas para inválidos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('159','3','Fabricación de otros tipos de equipo de transporte n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('160','3','Fabricación de muebles',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('161','3','Fabricación de joyas y artículos conexos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('162','3','Fabricación de bisutería y artículos conexos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('163','3','Fabricación de instrumentos musicales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('164','3','Fabricación de artículos de deporte',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('165','3','Fabricación de juegos y juguetes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('166','3','Fabricación de instrumentos y materiales médicos y odontológicos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('167','3','Otras industrias manufactureras n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('168','3','Reparación de productos elaborados de metal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('169','3','Reparación de maquinaria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('170','3','Reparación de equipo electrónico y óptico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('171','3','Reparación de equipo eléctrico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('172','3','Reparación de equipo de transporte, excepto vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('173','3','Reparación de otros tipos de equipo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('174','3','Instalación de maquinaria y equipo industriales',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('175','4','Generación, transmisión y distribución de energía eléctrica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('176','4','Fabricación de gas; distribución de combustibles gaseosos por tuberías',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('177','4','Suministro de vapor y de aire acondicionado',NULL,NULL,NULL);");
        
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('178','5','Captación, tratamiento y distribución de agua',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('179','5','Evacuación de aguas residuales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('180','5','Recolección de desechos no peligrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('181','5','Recolección de desechos peligrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('182','5','Tratamiento y eliminación de desechos no peligrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('183','5','Tratamiento y eliminación de desechos peligrosos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('184','5','Recuperación de materiales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('185','5','Actividades de descontaminación y otros servicios de  gestión de desechos',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('186','6','Construcción de edificios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('187','6','Construcción de carreteras y líneas de ferrocarril',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('188','6','Construcción de proyectos de servicios públicos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('189','6','Construcción de otras obras de ingeniería civil',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('190','6','Demolición del terreno',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('191','6','Preparación del terreno',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('192','6','Instalaciones eléctricas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('193','6','Fontanería (plomería, gasfitería) e instalación de calefacción y aire acondicionado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('194','6','Otras instalaciones para obras de construcción',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('195','6','Terminación y acabado de edificios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('196','6','Otras actividades especializadas de construcción',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('197','7','Venta de vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('198','7','Mantenimiento y reparación de vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('199','7','Venta de partes, piezas y accesorios para vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('200','7','Venta, mantenimiento y reparación de motocicletas y de sus partes, piezas y accesorios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('201','7','Venta al por mayor a cambio de una comision o por contrato',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('202','7','Venta al por mayor de materias primas agropecuarias y animales vivos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('203','7','Venta al por mayor de alimentos, bebidas y tabaco',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('204','7','Venta al por mayor de textiles, prendas de vestir y calzado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('205','7','Venta al por mayor de otros enseres domésticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('206','7','Venta al por mayor de computadoras, equipo y programas informáticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('207','7','Venta al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('208','7','Venta al por mayor de maquinaria, equipo y materiales agropecuarios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('209','7','Venta al por mayor de otros tipos de maquinaria y equipo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('210','7','Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('211','7','Venta al por mayor de metales y minerales metalíferos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('212','7','Venta al por mayor de materiales para la construcción, artículos de ferretería, equipo, materiales de fontanería (plomeria)',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('213','7','Venta al por mayor de desperdicios, desechos, chatarra y otros productos n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('214','7','Venta al por mayor de otros productos no especializado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('215','7','Venta al por menor en comercios no especializados con predominio de la venta de alimentos, bebidas o tabaco',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('216','7','Otras actividades de venta al por menor en comercios no especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('217','7','Venta al por menor de alimentos en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('218','7','Venta al por menor de bebidas en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('219','7','Venta al por menor de tabaco en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('220','7','Venta al por menor de combustibles para vehículos automotores en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('221','7','Venta al por menor de computadores, equipo periférico, programas informáticos y equipo de telecomunicaciones en comercio',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('222','7','Venta al por menor de equipo de sonido y vídeo en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('223','7','Venta al por menor de productos textiles en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('224','7','Venta al por menor de artículos de ferretería, pinturas y productos de vidrio en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('225','7','Venta al por menor de tapices, alfombras y cubrimientos para paredes y pisos en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('226','7','Venta al por menor de aparatos eléctricos de uso doméstico, muebles, equipo de iluminación y otros enseres domésticos en',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('227','7','Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('228','7','Venta al por menor de grabaciones de música y de vídeo en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('229','7','Venta al por menor de equipo de deporte en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('230','7','Venta al por menor de juegos y juguetes en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('231','7','Venta al por menor de prendas de vestir, calzado y artículos de cuero en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('232','7','Venta al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('233','7','Venta al por menor de otros productos nuevos en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('234','7','Venta al por menor de artículos de segunda mano en comercios especializados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('235','7','Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y mercados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('236','7','Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y mercados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('237','7','Venta al por menor de otros productos en puestos de venta y mercados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('238','7','Venta al por menor por correo y por internet',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('239','7','Otras actividades de venta al por menor no realizadas en comercios, puestos de venta o mercados',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('240','8','Transporte interurbano de pasajeros por ferrocarril',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('241','8','Transporte de carga por ferrocarril',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('242','8','Transporte urbano y suburbano de pasajeros por vía terrestre',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('243','8','Otras actividades de transporte de pasajeros por vía terrestre',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('244','8','Transporte de carga por carretera',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('245','8','Transporte por tuberías',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('246','8','Transporte de pasajeros marítimo y de cabotaje',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('247','8','Transporte de carga marítimo y de cabotaje',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('248','8','Transporte de pasajeros por vías de navegación interiores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('249','8','Transporte de carga, por vías de navegación interiores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('250','8','Transporte de pasajeros por vía aérea',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('251','8','Transporte de carga por vía aérea',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('252','8','Almacenamiento y depósito',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('253','8','Actividades de servicios vinculadas al transporte terrestre',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('254','8','Actividades de servicios vinculadas al transporte acuático',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('255','8','Actividades de servicios vinculadas al transporte aéreo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('256','8','Manipulación de carga',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('257','8','Otras actividades de apoyo al transporte',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('258','8','Actividades postales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('259','8','Actividades de mensajería',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('260','9','Actividades de alojamiento para estancias cortas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('261','9','Actividades de campamentos, parques de vehículos de recreo y parques de caravanas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('262','9','Otras actividades de alojamiento',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('263','9','Actividades de restaurantes y de servicio móvil de comidas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('264','9','Suministro de comidas por encargo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('265','9','Otras actividades de servicio de comidas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('266','9','Actividades de servicio de bebidas',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('267','10','Publicación de libros, periódicos y otras actividades de publicación',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('268','10','Publicación de directorios y de listas de correo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('269','10','Publicación de periódicos, diarios y revistas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('270','10','Otras publicaciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('271','10','Publicación de programas informáticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('272','10','Actividades de producción de películas cinematográficas, vídeos y programas de televisión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('273','10','Actividades de postproducción de películas cinematográficas, vídeos y programas de televisión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('274','10','Actividades de distribución de películas cinematográficas, vídeos y programas de televisión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('275','10','Actividades de exhibición de películas cinematográficas y cintas de vídeo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('276','10','Actividades de grabación de sonido y edición de música',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('277','10','Transmisiones de radio',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('278','10','Programación y transmisiones de televisión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('279','10','Actividades de telecomunicaciones alámbrica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('280','10','Actividades de telecomunicaciones inalámbricas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('281','10','Actividades de telecomunicaciones por satélite',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('282','10','Otras actividades de telecomunicaciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('283','10','Actividades de programación informática',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('284','10','Actividades de consultoría de informática y de gestión de instalaciones informáticas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('285','10','Otras actividades de tecnología de la información y de servicios informáticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('286','10','Procesamiento de datos, hospedaje y actividades conexas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('287','10','Portales web',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('288','10','Actividades de agencias de noticias',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('289','10','Otras actividades de servicios de información n.c.p',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('290','11','Banca central',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('291','11','Otros tipos de intermediación monetaria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('292','11','Actividades de sociedades de cartera',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('293','11','Fondos y sociedades de inversión y entidades financieras similares',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('294','11','Arrendamiento financiero',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('295','11','Otras actividades de concesión de crédito',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('296','11','Otras actividades de servicios financieros, excepto las de seguros y fondos de pensiones, n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('297','11','Seguros de vida',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('298','11','Seguros generales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('299','11','Reaseguros',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('300','11','Fondos de pensión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('301','11','Administración de mercados financieros',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('302','11','Corretaje de valores y de contratos de productos básicos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('303','11','Otras actividades auxiliares a las actividades de servicios financieros',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('304','11','Evaluación de riesgos y daños',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('305','11','Actividades de los agentes y corredores de seguro',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('306','11','Otras actividades auxiliares de seguros y fondos de pensiones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('307','11','Actividades de gestión de fondos',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('308','12','Actividades inmobiliarias realizadas con bienes propios o arrendados',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('309','12','Actividades inmobiliarias realizadas a cambio de una retribución o por contrato',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('310','13','Actividades jurídicas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('311','13','Actividades de contabilidad, teneduría de libros y auditorias; consultoría fiscal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('312','13','Actividades de oficinas principales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('313','13','Actividades de consultoría de gestión',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('314','13','Actividades de arquitectura e ingeniería y actividades conexas de consultoría técnica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('315','13','Ensayos y análisis técnicos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('316','13','Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('317','13','Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('318','13','Publicidad',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('319','13','Estudios de mercado y encuestas de opinión pública',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('320','13','Actividades especializadas de diseño',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('321','13','Actividades de fotografía',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('322','13','Otras actividades profesionales, científicas y técnicas n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('323','13','Actividades veterinarias',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('324','14','Alquiler de vehículos automotores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('325','14','Alquiler de equipo recreativo y deportivo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('326','14','Alquiler de cintas de video y discos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('327','14','Alquiler otros efectos personales y artículos de uso domésticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('328','14','Alquiler de otros tipos de maquinaria, equipo y bienes tangibles',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('329','14','Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('330','14','Actividades de agencias de empleo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('331','14','Actividades de agencias de empleo temporal',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('332','14','Otras actividades de dotación de recursos humanos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('333','14','Actividades de agencias de viajes',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('334','14','Actividades de operadores turísticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('335','14','Otros servicios de reservas y actividades conexas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('336','14','Actividades de seguridad privada',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('337','14','Actividades de servicios de sistemas de seguridad',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('338','14','Actividades de investigación',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('339','14','Limpieza general de edificios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('340','14','Otras actividades de limpieza de edificios e instalaciones industriales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('341','14','Actividades de paisajismo y servicios de mantenimiento conexos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('342','14','Actividades combinadas de servicios administrativos de oficina',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('343','14','Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('344','14','Actividades de centros de llamadas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('345','14','Organización de convenciones y exposiciones comerciales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('346','14','Actividades de agencias de cobro y agencias de calificación crediticia',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('347','14','Actividades de envasado y empaquetado',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('348','14','Otras actividades de servicios de apoyo a empresas n.c.p',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('349','15','Actividades de la administración pública en general',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('350','15','Regulación de las actividades de organismos que prestan servicios sanitarios, educativos, culturales y otros servicios',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('351','15','Regulación y facilitación de la actividad económica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('352','15','Relaciones exteriores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('353','15','Actividades de defensa',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('354','15','Actividades de mantenimiento del orden público y de seguridad',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('355','15','Actividades de planes de seguridad social de afiliación obligatoria',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('356','16','Enseñanza preprimaria y primaria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('357','16','Enseñanza secundaria de formación general',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('358','16','Enseñanza de formación técnica y profesional',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('359','16','Enseñanza superior',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('360','16','Enseñanza deportiva y recreativa',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('361','16','Enseñanza cultural',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('362','16','Otros tipos de enseñanza n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('363','16','Actividades de apoyo a la enseñanza',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('364','17','Actividades de hospitales y clínicas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('365','17','Actividades de médicos y odontólogos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('366','17','Otras actividades de atención de la salud humana',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('367','17','Actividades de atención de enfermería en instituciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('368','17','Actividades de atención en instituciones para personas con retraso mental, enfermos mentales y toxicómanos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('369','17','Actividades de atención en instituciones para personas de edad y personas con discapacidad',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('370','17','Otras actividades de atención en instituciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('371','17','Actividades de asistencia social sin alojamiento para personas de edad y personas con discapacidad',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('372','17','Otras actividades de asistencia social sin alojamiento',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('373','18','Actividades creativas, artísticas y de entretenimiento',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('374','18','Actividades de bibliotecas y archivos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('375','18','Actividades de museos y gestión de lugares y edificios históricos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('376','18','Actividades de jardines botánicos y zoológicos y reservas naturales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('377','18','Actividades de juegos de azar y apuestas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('378','18','Explotación de instalaciones deportivas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('379','18','Actividades de clubes deportivos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('380','18','Otras actividades deportivas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('381','18','Actividades de parques de atracciones y parques temáticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('382','18','Otras actividades de esparcimiento y recreativas n.c.p',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('383','19','Actividades de asociaciones empresariales y de empleadores',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('384','19','Actividades de asociaciones profesionales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('385','19','Actividades de sindicatos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('386','19','Actividades de organizaciones religiosas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('387','19','Actividades de organizaciones políticas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('388','19','Actividades de otras asociaciones n.c.p',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('389','19','Reparación de computadoras y equipo periférico',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('390','19','Reparación de equipo de comunicaciones',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('391','19','Reparación de aparatos electrónicos de consumo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('392','19','Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('393','19','Reparación de calzado y artículos de cuero',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('394','19','Reparación de muebles y accesorios domésticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('395','19','Reparación de otros bienes personales y enseres domésticos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('396','19','Lavado y limpieza, incluida la limpieza en seco, de productos textiles y de piel',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('397','19','Actividades de peluquería y otros tratamientos de belleza',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('398','19','Pompas fúnebres y actividades conexas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('399','19','Otras actividades de servicios personales n.c.p',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('400','20','Actividades de Organizaciones y Órganos Extraterritoriales',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('401','21','Eduación inicial',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('402','21','Educación primaria y secundaria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('403','21','Educación superior',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('404','21','Inclusión económica y social',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('405','21','Salud',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('406','21','Movilidad Humana',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('407','21','Deporte',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('408','21','Cultura',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('409','21','Vivienda',NULL,NULL,NULL);");
    
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('410','22','Recursos naturales no renovables',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('411','22','Medio Ambiente',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('412','22','Agua',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('413','23','Energía',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('414','23','Transporte',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('415','23','Obras públicas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('416','23','Gestión de Riesgos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('417','23','Telecomunicaciones',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('418','24','Derechos ciudadanos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('419','24','Derechos humanos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('420','24','Seguridad ciudadana',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('421','24','Institucionalidad jurídica',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('422','24','Derechos laborales',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('423','24','Seguridad',NULL,NULL,NULL);");

        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('424','25','Ámbito económico y tributario',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('425','25','Finanzas',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('426','25','Comercio exterior',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('427','25','Agricultura, ganadería y pesca',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('428','25','Agroindustria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('429','25','Industria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('430','25','Turismo',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('431','25','Economía Popular y Solidaria',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('432','25','Artesanos',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('433','25','Otros producción',NULL,NULL,NULL);");
        /*
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('434','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('435','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('436','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('437','19','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('438','19','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('439','19','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('440','20','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('441','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('442','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('443','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('444','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('445','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('446','21','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('447','19','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('448','19','',NULL,NULL,NULL);");
        DB::insert("insert into tipo_subsector (id, sector_id, nombre, created_at, updated_at, deleted_at) values('449','19','',NULL,NULL,NULL);");
    */
    }
}
